import { afterEach,describe,expect,it } from 'bun:test'
import { ControlPlaneStore } from '../control-plane'
import type { FleetDriver,FleetServer,ServerFacts,ServerProvider } from './index'
import { FleetService,FleetStore } from './index'
import { SshFleetDriver } from './ssh-driver'
import { DurableQueueWorker } from '../queue'
import { createFleetQueueHandlers } from './queue'
const controls:ControlPlaneStore[]=[];afterEach(()=>{while(controls.length)controls.pop()!.close()})
class Driver implements FleetDriver{fingerprint='SHA256:first';reachable=true;facts:ServerFacts={os:'Ubuntu 24.04',arch:'x86_64',cpuCores:4,memoryBytes:8_000,diskBytes:100_000,diskFreeBytes:80_000,dnsOk:true,timeSkewSeconds:1,tools:{curl:'8',tar:'1.35'},ports:[22,80,443],privilege:'sudo',runtimeVersions:{docker:'27'}};constructor(readonly provider:ServerProvider){}async discover(){return[]}async test(){return{reachable:this.reachable,hostKeyAlgorithm:'ssh-ed25519',hostKeyFingerprint:this.fingerprint,latencyMs:5}}async validate(){return this.facts}async bootstrap(){return{version:'1'}}capabilities(){return{validate:{supported:true},bootstrap:{supported:true},drain:{supported:true},terminate:{supported:this.provider!=='ssh',reason:this.provider==='ssh'?'Existing boxes are inventory-only.':undefined}}}}
function fixture(){const control=new ControlPlaneStore({path:':memory:'});controls.push(control);const organization=control.createOrganization({slug:'acme',name:'Acme'}),project=control.createProject({organizationId:organization.id,slug:'cloud',name:'Cloud'}),drivers=[new Driver('aws'),new Driver('hetzner'),new Driver('ssh')],service=new FleetService(new FleetStore(control),drivers);return{control,organization,project,drivers,service}}
const input=(target:ReturnType<typeof fixture>,provider:ServerProvider,providerId:string,name=provider)=>({organizationId:target.organization.id,projectId:target.project.id,name:`${name}-node`,provider,providerId,region:'west',endpoint:`${name}.example.test`,sshUser:'deploy',credentialRef:`secret://fleet/${name}`,roles:['application' as const],labels:{pool:'production'}})
describe('provider-neutral fleet enrollment',()=>{it('onboards AWS, Hetzner, and existing SSH boxes into one inventory',async()=>{const target=fixture();for(const [provider,id] of [['aws','i-1'],['hetzner','h-1'],['ssh','box-1']] as const){const enrolled=target.service.enroll(input(target,provider,id));await target.service.test(enrolled.id);expect(await target.service.validate(enrolled.id)).toMatchObject({status:'ready',capacity:{cpu:4}})}expect(target.service.store.list(target.project.id).map(v=>v.provider)).toEqual(['aws','hetzner','ssh']);expect(target.service.store.list(target.project.id)[2]?.capabilities.terminate.supported).toBe(false)})
it('reconciles provider identity across address changes and blocks host-key rotation',async()=>{const target=fixture(),first=target.service.enroll(input(target,'aws','i-stable'));await target.service.test(first.id);const moved=target.service.enroll({...input(target,'aws','i-stable'),endpoint:'moved.example.test'});expect(moved.id).toBe(first.id);expect(moved.endpoint).toBe('moved.example.test');target.drivers[0]!.fingerprint='SHA256:rotated';expect(await target.service.test(first.id)).toMatchObject({trustState:'rotation_pending',status:'degraded'});expect(()=>target.service.reviewHostKey(first.id,'wrong')).toThrow();expect(target.service.reviewHostKey(first.id,'SHA256:rotated').trustState).toBe('pinned')})
it('reports actionable validation, durable bootstrap, heartbeat, drain, and archive state',async()=>{const target=fixture(),server=target.service.enroll(input(target,'ssh','box-2'));await target.service.test(server.id);target.drivers[2]!.facts={os:'Linux',arch:'mips',dnsOk:false,timeSkewSeconds:90,tools:{}};const invalid=await target.service.validate(server.id);expect(invalid.validation?.findings.map(v=>v.code)).toEqual(['arch.unsupported','tool.curl','tool.tar','time.skew','dns.failed']);expect(()=>target.service.bootstrap(server.id,true)).toThrow('healthy');target.drivers[2]!.facts={arch:'arm64',dnsOk:true,timeSkewSeconds:0,tools:{curl:'8',tar:'1'}};await target.service.validate(server.id);expect(target.service.bootstrap(server.id,false)).toMatchObject({preview:true});expect(target.service.bootstrap(server.id,true)).toMatchObject({operation:{kind:'fleet.bootstrap'}});expect(target.service.heartbeat(server.id,{usage:{cpu:20,memoryBytes:1000}})).toMatchObject({status:'ready',usage:{cpu:20}});expect(target.service.drain(server.id).status).toBe('draining');expect(target.service.drain(server.id,true).status).toBe('drained');expect(target.service.uncordon(server.id).status).toBe('ready');expect(()=>target.service.archive(server.id,'wrong')).toThrow();expect(target.service.archive(server.id,server.name).status).toBe('archived')})})
describe('strict SSH fleet driver',()=>{it('pins scanned keys and parses constrained validation facts',async()=>{const transport={scan:async()=>({algorithm:'ssh-ed25519',key:Buffer.from('key').toString('base64')}),exec:async()=>({code:0,stdout:JSON.stringify({arch:'arm64',dnsOk:true,tools:{curl:'8',tar:'1'}}),stderr:''})},driver=new SshFleetDriver('ssh',transport),server:any={trustState:'pinned',sshPort:22,sshUser:'deploy',endpoint:'box.example.test'};expect(await driver.test(server)).toMatchObject({reachable:true,hostKeyAlgorithm:'ssh-ed25519'});expect(await driver.validate(server)).toMatchObject({arch:'arm64'});expect(driver.capabilities().terminate.supported).toBe(false)})})
describe('fleet bootstrap worker',()=>{it('executes the persisted reviewed plan and records its version',async()=>{const target=fixture(),server=target.service.enroll(input(target,'aws','i-worker'));await target.service.test(server.id);await target.service.validate(server.id);target.service.bootstrap(server.id,true);expect(await new DurableQueueWorker(target.service.queue,createFleetQueueHandlers(target.service.store,target.drivers)).drain()).toMatchObject([{terminalState:'succeeded'}]);expect(target.service.store.get(server.id)?.bootstrapVersion).toBe('1')})})
