/**
 * Serialize the resolved cloud config into a self-contained module for the
 * dashboard to read on the box.
 *
 * Copying the project's `cloud.config.ts` verbatim does not work: a real config
 * imports things. Stacks' does
 * `import { servers } from '~/cloud/servers'` and `import { env } from
 * '@stacksjs/env'` — neither the path alias nor the package exists in the
 * dashboard's release dir, so the import would throw and the dashboard would
 * come up describing nothing.
 *
 * The deploy machine has already resolved the config to a plain object, so we
 * ship THAT as a literal. No imports, no aliases, nothing to resolve.
 *
 * Credentials are stripped on the way out (see {@link redactForDashboard}).
 */
import type { CloudConfig } from '@ts-cloud/core'

/** Blank every value in a record, keeping its keys. */
function blankValues(record: Record<string, unknown> | undefined): Record<string, string> | undefined {
  if (!record || typeof record !== 'object') return record as undefined
  return Object.fromEntries(Object.keys(record).map((key) => [key, '']))
}

/**
 * Strip everything the dashboard does not need to read.
 *
 * Two rules:
 *
 * 1. **No credentials.** The Hetzner API token is the big one: it controls the
 *    whole cloud account (create and destroy any server), and unlike a site's
 *    own secrets it is otherwise NOT on the box at all. Putting it in the
 *    dashboard's release would turn a dashboard compromise into an account
 *    compromise. AWS credentials go for the same reason.
 *
 * 2. **Env keys, not env values.** The dashboard only ever displays which env
 *    vars a site defines, never their values — so ship the keys and blank the
 *    values. The running site has its own `.env` on the box regardless; there
 *    is no reason for a second copy to sit in the dashboard's directory.
 */
export function redactForDashboard(config: CloudConfig): Record<string, any> {
  // A JSON round-trip both deep-clones and drops functions (deploy hooks),
  // which could never run on the box and would not serialize anyway.
  const safe = JSON.parse(JSON.stringify(config ?? {})) as Record<string, any>

  if (safe.hetzner) delete safe.hetzner.apiToken
  // The whole AWS block is account credentials + region hints the box dashboard
  // has no use for in box mode.
  delete safe.aws

  for (const site of Object.values(safe.sites ?? {}) as Array<Record<string, any>>) {
    if (site?.env) site.env = blankValues(site.env)
    if (site?.environment) site.environment = blankValues(site.environment)
  }

  for (const env of Object.values(safe.environments ?? {}) as Array<Record<string, any>>) {
    if (env?.variables) env.variables = blankValues(env.variables)
  }

  for (const db of Object.values(safe.infrastructure?.databases ?? {}) as Array<Record<string, any>>) {
    if (db?.password) db.password = ''
  }

  return safe
}

/**
 * The `cloud.config.ts` module text shipped in the dashboard's release. Reads
 * as a plain literal so bun can import it on the box with nothing installed
 * beyond the ts-cloud package itself.
 */
export function serializeDashboardConfig(config: CloudConfig): string {
  const safe = redactForDashboard(config)
  return [
    '// Generated by ts-cloud for the management dashboard — do not edit.',
    '//',
    "// This is the project's resolved cloud config, inlined so it needs no",
    '// imports on the box. Credentials are deliberately absent.',
    `export default ${JSON.stringify(safe, null, 2)}`,
    '',
  ].join('\n')
}
