import type { JsonValue } from '../control-plane'
import type { RegionalProviderDriver,RegionalTarget,RegionalTopology,RegionalTrafficRoute,ReplicationChannel } from './types'
export interface AwsRegionalTransport{
  applyCloudFormation(input:{region:string;stackId?:string;revision:string;manifest:JsonValue}):Promise<{stackId:string}>
  deleteCloudFormation(input:{region:string;stackId:string;retainData:boolean}):Promise<void>
  stackHealth(input:{region:string;stackId:string}):Promise<{healthy:boolean;evidence:Record<string,JsonValue>}>
  configureS3Replication(input:{sourceRegion:string;targetRegion:string;config:Record<string,JsonValue>}):Promise<{checkpoint:string;lagSeconds:number}>
  configureDynamoGlobalTable(input:{sourceRegion:string;targetRegion:string;config:Record<string,JsonValue>}):Promise<{checkpoint:string;lagSeconds:number}>
  replicateSecrets(input:{sourceRegion:string;targetRegion:string;config:Record<string,JsonValue>}):Promise<{checkpoint:string;lagSeconds:number}>
  verifyReplication(input:{kind:ReplicationChannel['kind'];sourceRegion:string;targetRegion:string;checkpoint?:string}):Promise<{healthy:boolean;checkpoint:string;lagSeconds:number}>
  applyEdge(input:{hostname:string;weights:Record<string,number>;route53:boolean;cloudFront:boolean;waf:boolean}):Promise<{providerState:Record<string,JsonValue>}>
}
export class AwsRegionalDriver implements RegionalProviderDriver{readonly provider='aws';constructor(private transport:AwsRegionalTransport){}async applyStack({target,revision,manifest}:{target:RegionalTarget;revision:string;manifest:JsonValue;signal:AbortSignal}):Promise<{stackId:string}>{return this.transport.applyCloudFormation({region:target.region,stackId:target.stackId,revision,manifest})}async deleteStack({target,retainData}:{target:RegionalTarget;retainData:boolean;signal:AbortSignal}):Promise<void>{if(!target.stackId)return;await this.transport.deleteCloudFormation({region:target.region,stackId:target.stackId,retainData})}async health({target}:{target:RegionalTarget}):Promise<{healthy:boolean;evidence:Record<string,JsonValue>}>{if(!target.stackId)return{healthy:false,evidence:{reason:'stack is not provisioned'}};return this.transport.stackHealth({region:target.region,stackId:target.stackId})}async configureReplication({channel}:{channel:ReplicationChannel;topology:RegionalTopology}):Promise<{checkpoint:string;lagSeconds:number}>{const input={sourceRegion:channel.sourceRegion,targetRegion:channel.targetRegion,config:channel.config};if(channel.kind==='s3')return this.transport.configureS3Replication(input);if(channel.kind==='dynamodb')return this.transport.configureDynamoGlobalTable(input);return this.transport.replicateSecrets(input)}async verifyReplication({channel}:{channel:ReplicationChannel;topology:RegionalTopology}):Promise<{healthy:boolean;checkpoint:string;lagSeconds:number}>{return this.transport.verifyReplication({kind:channel.kind,sourceRegion:channel.sourceRegion,targetRegion:channel.targetRegion,checkpoint:channel.checkpoint})}async applyTraffic({route,weights}:{route:RegionalTrafficRoute;topology:RegionalTopology;weights:Record<string,number>}):Promise<{providerState:Record<string,JsonValue>}>{return this.transport.applyEdge({hostname:route.hostname,weights,route53:route.dnsProvider==='route53',cloudFront:route.cdnEnabled,waf:route.wafEnabled})}}
