import type { JsonValue } from '../control-plane'
import { DurableOperationQueue } from '../queue'
import type { RegionalOperationKind,RegionalTopology } from './types'
import { RegionStore } from './store'
export class RegionService{readonly queue:DurableOperationQueue;constructor(readonly store:RegionStore,queue?:DurableOperationQueue){this.queue=queue??new DurableOperationQueue(store.control)}
create(input:Parameters<RegionStore['create']>[0]):RegionalTopology{return this.store.create(input)}
plan(id:string,kind:RegionalOperationKind,target?:string):string[]{const value=this.store.get(id);if(!value)throw new Error('Regional topology was not found.');const regions=this.store.targets(id),channels=this.store.channels(id);if(kind==='rollout')return[...regions.filter(v=>v.role==='secondary').map(v=>`apply:${v.region}`),...regions.filter(v=>v.role==='primary').map(v=>`apply:${v.region}`),...channels.map(v=>`replicate:${v.kind}:${v.targetRegion}`),'traffic:activate'];if(kind==='failover'||kind==='failback')return[`health:${target}`,`replication:${target}`,`traffic:${target}`,`roles:${target}`];if(kind==='destroy')return['traffic:drain',...regions.filter(v=>v.role==='secondary').map(v=>`delete:${v.region}`),...regions.filter(v=>v.role==='primary').map(v=>`delete:${v.region}`),'complete'];return['observe','repair']}
enqueue(input:{topologyId:string;kind:RegionalOperationKind;targetRegion?:string;revision?:string;manifest?:JsonValue;confirmation?:string;deleteData?:boolean}){const topology=this.store.get(input.topologyId);if(!topology)throw new Error('Regional topology was not found.');if(['failover','failback'].includes(input.kind)&&(!input.targetRegion||!topology.regions.some(v=>v.region===input.targetRegion)))throw new Error('A topology target region is required.');if(input.kind==='failover'&&input.targetRegion===topology.activeRegion)throw new Error('Target region is already active.');if((input.kind==='destroy'||input.deleteData)&&input.confirmation!==topology.name)throw new Error('Exact topology name confirmation is required.');if(input.deleteData&&topology.dataPolicy.retainOnDestroy)throw new Error('Topology policy requires regional data retention.');if(input.kind==='rollout'&&!/^[A-Za-z0-9._:@/-]{7,200}$/.test(input.revision??''))throw new Error('An immutable revision is required.');const plan=this.plan(topology.id,input.kind,input.targetRegion),execution=this.store.createExecution({topologyId:topology.id,kind:input.kind,requestedRegion:input.targetRegion,revision:input.revision,plan}),operation=this.queue.enqueue({projectId:topology.projectId,environmentId:topology.environmentId,kind:`region.${input.kind}`,input:{executionId:execution.id,manifest:input.manifest??{},deleteData:input.deleteData===true},lockKey:`regional-topology:${topology.id}`,providerKey:'multi-region',timeoutSeconds:7200,cancellationMode:'provider_non_cancellable',resumePolicy:'requeue',maxAttempts:3}).operation;this.store.updateExecution(execution.id,{operationId:operation.id});return{execution:this.store.execution(execution.id)!,operation}}
}
