/**
 * AWS Integration Layer
 * Direct API calls for AWS services (no SDK dependencies)
 */

export * from './client'
export * from './cloudformation'
export * from './s3'
export * from './cloudfront'
export * from './route53'
export * from './route53-domains'
export * from './acm'
export * from './ecr'
export * from './ecs'
export * from './sts'
export * from './ssm'
export * from './secrets-manager'
export * from './ses'
export * from './email'
export * from './sns'
export * from './sqs'
export * from './lambda'
export * from './cloudwatch-logs'
export * from './connect'
export * from './elbv2'
export * from './pinpoint'
export * from './rds'
export * from './dynamodb'
export * from './opensearch'
export * from './transcribe'
export * from './bedrock'
export * from './eventbridge'
export * from './elasticache'
export * from './scheduler'
export * from './iam'
export * from './imap-server'
export * from './smtp-server'
export * from './pinpoint-sms-voice'
export * from './sms'
export * from './voice'
export * from './support'
export * from './setup-sms'
