import { afterEach, describe, expect, it } from 'bun:test'
import { ControlPlaneStore } from '../control-plane'
import { DurableOperationQueue } from '../queue'
import type { PersistentVolume, VolumeAttachment, VolumeDriver, VolumeDriverObservation, VolumeSnapshot } from './model'
import { createVolumeQueueHandlers, validateMountPath, volumeCapabilities, VolumeService } from './service'
import { VolumeStore } from './store'

const controls:ControlPlaneStore[]=[]
class MemoryDriver implements VolumeDriver {
  readonly provider='docker';readonly type='docker' as const;created=new Map<string,VolumeDriverObservation>();writes=new Map<string,string>()
  capabilities(){return volumeCapabilities(['create','attach','detach','resize','snapshot','restore','delete','adopt','usage'],{resize:{supported:true,online:false,minimumBytes:10}})}
  async discover(){return[...this.created.values()]}
  async create(volume:PersistentVolume){const result={providerId:`named-${volume.id}`,capacityBytes:volume.capacityBytes,usedBytes:0,filesystem:'overlay',encrypted:volume.encrypted};this.created.set(volume.id,result);return result}
  async attach(_volume:PersistentVolume,_attachment:VolumeAttachment){ }
  async detach(_volume:PersistentVolume,_attachment:VolumeAttachment,_options:{force:boolean}){ }
  async resize(volume:PersistentVolume,capacityBytes:number){const result={...this.created.get(volume.id)!,capacityBytes};this.created.set(volume.id,result);return result}
  async snapshot(volume:PersistentVolume,_snapshot:VolumeSnapshot){return{providerId:`snap-${volume.id}`,sizeBytes:this.writes.get(volume.id)?.length??0,checksum:'sha256:test'}}
  async restore(_volume:PersistentVolume,_snapshot:VolumeSnapshot,target:PersistentVolume){return{providerId:`restored-${target.id}`}}
  async delete(volume:PersistentVolume){this.created.delete(volume.id)}
  async usage(volume:PersistentVolume){return this.created.get(volume.id)??{}}
}
function fixture(){const now={value:new Date('2026-07-21T12:00:00.000Z')},control=new ControlPlaneStore({path:':memory:',now:()=>now.value});controls.push(control);const organization=control.createOrganization({slug:'acme',name:'Acme'}),project=control.createProject({organizationId:organization.id,slug:'web',name:'Web'}),environment=control.createEnvironment({projectId:project.id,slug:'production',name:'Production',kind:'production'}),resource=control.createResource({projectId:project.id,environmentId:environment.id,kind:'application',slug:'api',name:'API'}),store=new VolumeStore(control,()=>now.value),queue=new DurableOperationQueue(control,{now:()=>now.value,workerId:'volume-test'}),driver=new MemoryDriver(),service=new VolumeService(store,[driver],queue,()=>now.value);return{now,control,organization,project,environment,resource,store,queue,driver,service}}
afterEach(()=>{while(controls.length)controls.pop()!.close()})

describe('persistent volume lifecycle',()=>{
  it('preserves stable identity through create, attach, resize, snapshot, detach, and delete',async()=>{const target=fixture(),created=target.service.create({organizationId:target.organization.id,projectId:target.project.id,environmentId:target.environment.id,name:'uploads',provider:'docker',type:'docker',capacityBytes:100,encrypted:true});let handlers=createVolumeQueueHandlers(target.store,[target.driver]);await target.queue.runOne(handlers);const id=created.volume.id;expect(target.store.get(id)).toMatchObject({id,status:'available',providerId:`named-${id}`});const attached=target.service.attach(id,{resourceId:target.resource.id,targetPath:'/app/uploads',uid:1000,gid:1000,mode:'0750'});await target.queue.runOne(handlers);expect(target.store.attachment(attached.attachment!.id)?.observedState).toBe('attached');expect(()=>target.service.resize(id,200)).toThrow('drain');target.service.resize(id,200,{drained:true});await target.queue.runOne(handlers);target.driver.writes.set(id,'persistent bytes');target.service.snapshot(id);await target.queue.runOne(handlers);expect(target.store.snapshots(id)[0]).toMatchObject({status:'available',sizeBytes:16});expect(target.store.get(id)?.id).toBe(id);target.service.detach(id,attached.attachment!.id,{drained:true,unmounted:true});await target.queue.runOne(handlers);expect(target.store.get(id)?.status).toBe('available');target.service.delete(id,{recentAuthAt:target.now.value.toISOString(),confirmation:'uploads'});await target.queue.runOne(handlers);expect(target.store.get(id)?.status).toBe('deleted')})
  it('blocks dangerous paths, cross-tenant mounts, active deletion, and shrinking',async()=>{const target=fixture(),created=target.service.create({organizationId:target.organization.id,projectId:target.project.id,environmentId:target.environment.id,name:'database',provider:'docker',type:'docker',capacityBytes:100});await target.queue.runOne(createVolumeQueueHandlers(target.store,[target.driver]));for(const path of ['/','/etc/passwd','relative','/app/../etc'])expect(()=>validateMountPath(path)).toThrow();const other=target.control.createProject({organizationId:target.organization.id,slug:'other',name:'Other'}),foreign=target.control.createResource({projectId:other.id,kind:'application',slug:'foreign',name:'Foreign'});expect(()=>target.service.attach(created.volume.id,{resourceId:foreign.id,targetPath:'/data'})).toThrow('Cross-project');expect(()=>target.service.resize(created.volume.id,99,{drained:true})).toThrow('shrinking');const attached=target.service.attach(created.volume.id,{resourceId:target.resource.id,targetPath:'/data'});await target.queue.runOne(createVolumeQueueHandlers(target.store,[target.driver]));expect(()=>target.service.delete(created.volume.id,{recentAuthAt:target.now.value.toISOString(),confirmation:'database',backupOverride:true,backupOverrideConfirmation:'delete without backup database'})).toThrow('Detach');expect(()=>target.service.detach(created.volume.id,attached.attachment!.id)).toThrow('drain')})
  it('discovers and safely adopts provider orphans',async()=>{const target=fixture();target.driver.created.set('external',{providerId:'external-volume',capacityBytes:512,usedBytes:128,encrypted:true});const discovered=await target.service.discover({organizationId:target.organization.id,projectId:target.project.id,environmentId:target.environment.id});const orphan=discovered.find(item=>item.providerId==='external-volume')!;expect(target.store.inventory(target.project.id)).toMatchObject([{orphaned:true,usagePercent:25,backupState:'unprotected'}]);expect(target.service.adopt(orphan.id,{name:'imported'})).toMatchObject({name:'imported',status:'available',orphanedAt:undefined})})
})
