/**
 * Generates the bootstrap entry module that is bundled as the Lambda artifact's
 * top-level handler file. It imports the user's application entry plus the
 * runtime adapter, then re-exports the three Lambda handlers (`http`, `queue`,
 * `cli`) that API Gateway / SQS / EventBridge invoke.
 */

export interface BootstrapOptions {
  /** Import specifier for the user's app entry (absolute path or bare module). */
  entryImport: string
  /** Import specifier for the runtime adapter. @default './adapter' */
  adapterImport?: string
}

export function generateBootstrap(opts: BootstrapOptions): string {
  const adapter = opts.adapterImport ?? './adapter'
  // Forward slashes so the specifier is valid on every platform.
  const entry = opts.entryImport.replace(/\\/g, '/')
  return `// Generated by ts-cloud — serverless app bootstrap. Do not edit.
import * as __userModule from ${JSON.stringify(entry)}
import { resolveApp, createHandlers } from ${JSON.stringify(adapter)}

const __app = resolveApp(__userModule)
const __handlers = createHandlers(__app)

export const http = __handlers.http
export const queue = __handlers.queue
export const cli = __handlers.cli
`
}
