import type { ControlPlaneStore } from '../control-plane'
import type { CleanupCandidate,CleanupDriver,CleanupPlan,DisasterRecoveryDrill,DisasterRecoveryDriver,PlatformMaintenanceDriver,PlatformUpdateDocument,UpgradeTarget } from './types'
type Row=Record<string,unknown>
export interface PlatformMaintenanceTransport{download(input:{target:string,url:string,signal:AbortSignal}):Promise<{path:string;sha256:string}>;install(input:{target:string,path:string,version:string,signal:AbortSignal}):Promise<void>;health(input:{target:string,gate:Record<string,unknown>}):Promise<{healthy:boolean;evidence:Record<string,any>}>;rollback(input:{target:string,version:string,signal:AbortSignal}):Promise<void>}
export class TransportPlatformMaintenanceDriver implements PlatformMaintenanceDriver{constructor(private transport:PlatformMaintenanceTransport){}download(input:{target:UpgradeTarget;artifact:PlatformUpdateDocument['artifacts'][number];signal:AbortSignal}):Promise<{path:string;sha256:string}>{return this.transport.download({target:input.target.target,url:input.artifact.url,signal:input.signal})}install(input:{target:UpgradeTarget;path:string;version:string;signal:AbortSignal}):Promise<void>{return this.transport.install({target:input.target.target,path:input.path,version:input.version,signal:input.signal})}health(input:{target:UpgradeTarget;gate:Record<string,any>}):Promise<{healthy:boolean;evidence:Record<string,any>}>{return this.transport.health({target:input.target.target,gate:input.gate})}rollback(input:{target:UpgradeTarget;version:string;signal:AbortSignal}):Promise<void>{return this.transport.rollback({target:input.target.target,version:input.version,signal:input.signal})}}
const tables:Record<CleanupPlan['kind'],{select:string;remove:string}>={
  releases:{select:"SELECT id,created_at,0 bytes FROM releases WHERE project_id=? AND pinned=0 AND status IN ('failed','rolled_back','superseded') AND created_at<?",remove:'DELETE FROM releases WHERE id=?'},
  artifacts:{select:'SELECT a.id,a.created_at,a.size bytes FROM release_artifacts a WHERE a.organization_id=? AND NOT EXISTS(SELECT 1 FROM releases r WHERE r.artifact_id=a.id) AND a.created_at<?',remove:'DELETE FROM release_artifacts WHERE id=?'},
  operations:{select:"SELECT id,created_at,0 bytes FROM operations WHERE project_id=? AND state IN ('succeeded','failed','cancelled','timed_out') AND updated_at<?",remove:'DELETE FROM operations WHERE id=?'},
  logs:{select:"SELECT l.id,l.created_at,length(l.message) bytes FROM operation_logs l JOIN operations o ON o.id=l.operation_id WHERE o.project_id=? AND o.state IN ('succeeded','failed','cancelled','timed_out') AND l.created_at<?",remove:'DELETE FROM operation_logs WHERE id=?'},
  previews:{select:"SELECT id,created_at,0 bytes FROM preview_instances WHERE project_id=? AND status IN ('destroyed','failed') AND updated_at<?",remove:'DELETE FROM preview_instances WHERE id=?'},
  snapshots:{select:"SELECT id,created_at,size_bytes bytes FROM recovery_points WHERE project_id=? AND pinned=0 AND held=0 AND status IN ('failed','deleted') AND created_at<?",remove:'DELETE FROM recovery_points WHERE id=?'},
  orphaned_resources:{select:"SELECT id,created_at,COALESCE(capacity_bytes,0) bytes FROM persistent_volumes WHERE project_id=? AND status='orphaned' AND orphaned_at<?",remove:"UPDATE persistent_volumes SET status='deleted',deleted_at=datetime('now'),updated_at=datetime('now') WHERE id=? AND status='orphaned'"},
}
export class ControlPlaneCleanupDriver implements CleanupDriver{constructor(readonly kind:CleanupPlan['kind'],private control:ControlPlaneStore,private projectId:string,private organizationId:string){}async discover(criteria:CleanupPlan['criteria']):Promise<CleanupCandidate[]>{const days=Math.max(1,Math.min(3650,Number(criteria.olderThanDays??30))),cutoff=new Date(Date.now()-days*86_400_000).toISOString(),spec=tables[this.kind],scope=this.kind==='artifacts'?this.organizationId:this.projectId;const rows=this.control.database.query<Row,[string,string]>(spec.select).all(scope,cutoff);return rows.map(row=>({id:String(row.id),kind:this.kind,label:`${this.kind}:${String(row.id)}`,bytes:Number(row.bytes??0),metadata:{createdAt:String(row.created_at)}}))}async remove(candidate:CleanupCandidate):Promise<void>{const changed=this.control.database.run(tables[this.kind].remove,[candidate.id]).changes;if(changed!==1)throw new Error(`${candidate.label} changed or is no longer removable.`)}}
export interface DisasterRecoveryTransport{restore(input:{scenario:DisasterRecoveryDrill['scenario'];drill:DisasterRecoveryDrill;signal:AbortSignal}):Promise<{target:string;recoveryPointAt:string;evidence:Record<string,any>}>;verify(input:{scenario:DisasterRecoveryDrill['scenario'];drill:DisasterRecoveryDrill;target:string}):Promise<{healthy:boolean;evidence:Record<string,any>}>;cleanup(input:{scenario:DisasterRecoveryDrill['scenario'];drill:DisasterRecoveryDrill;target:string}):Promise<void>}
export class TransportDisasterRecoveryDriver implements DisasterRecoveryDriver{constructor(readonly scenario:DisasterRecoveryDrill['scenario'],private transport:DisasterRecoveryTransport){}restore(input:{drill:DisasterRecoveryDrill;signal:AbortSignal}):Promise<{target:string;recoveryPointAt:string;evidence:Record<string,any>}>{return this.transport.restore({scenario:this.scenario,...input})}verify(input:{drill:DisasterRecoveryDrill;target:string}):Promise<{healthy:boolean;evidence:Record<string,any>}>{return this.transport.verify({scenario:this.scenario,...input})}cleanup(input:{drill:DisasterRecoveryDrill;target:string}):Promise<void>{return this.transport.cleanup({scenario:this.scenario,...input})}}
