import { afterEach,describe,expect,it } from 'bun:test'
import { generateKeyPairSync,sign } from 'node:crypto'
import { ControlPlaneStore } from '../control-plane'
import { DurableQueueWorker } from '../queue'
import { canonicalJson,createMaintenanceQueueHandlers,MaintenanceService,MaintenanceStore } from './index'
import type { CleanupDriver,DisasterRecoveryDriver,PlatformMaintenanceDriver,PlatformUpdateDocument } from './index'
const controls:ControlPlaneStore[]=[];afterEach(()=>{while(controls.length)controls.pop()!.close()})
function fixture(){const control=new ControlPlaneStore({path:':memory:'});controls.push(control);const organization=control.createOrganization({slug:'acme',name:'Acme'}),project=control.createProject({organizationId:organization.id,slug:'cloud',name:'Cloud'}),actor=control.createActor({kind:'user',externalId:'operator',displayName:'Operator'}),store=new MaintenanceStore(control),service=new MaintenanceService(store),pair=generateKeyPairSync('ed25519'),trusted=store.addTrustedKey({organizationId:organization.id,name:'release',publicKeyPem:pair.publicKey.export({type:'spki',format:'pem'}).toString()}),document:PlatformUpdateDocument={version:'2.0.0',channel:'stable',publishedAt:'2026-01-01T00:00:00.000Z',minimumSchema:1,maximumSchema:99,minimumVersion:'1.0.0',artifacts:[{platform:process.platform,architecture:process.arch,url:'https://updates.example/ts-cloud',sha256:'a'.repeat(64),sizeBytes:100}],migrations:[{id:'schema-2',reversible:true,description:'upgrade'}]},signature=sign(null,Buffer.from(canonicalJson(document)),pair.privateKey).toString('base64'),manifest=store.importManifest({organizationId:organization.id,keyId:trusted.id,document,signature,current:{schemaVersion:35,currentVersion:'1.0.0',platform:process.platform,architecture:process.arch}});return{control,organization,project,actor,store,service,pair,trusted,document,signature,manifest}}
describe('signed platform updates',()=>{it('accepts only a trusted signature and records compatibility',()=>{const target=fixture();expect(target.manifest).toMatchObject({verificationStatus:'verified',compatibility:{compatible:true}});expect(()=>target.store.importManifest({organizationId:target.organization.id,keyId:target.trusted.id,document:{...target.document,version:'2.0.1'},signature:target.signature,current:{schemaVersion:35,currentVersion:'1.0.0',platform:process.platform,architecture:process.arch}})).toThrow('signature is invalid');target.store.revokeKey(target.trusted.id);expect(()=>target.store.importManifest({organizationId:target.organization.id,keyId:target.trusted.id,document:target.document,signature:target.signature,current:{schemaVersion:35,currentVersion:'1.0.0',platform:process.platform,architecture:process.arch}})).toThrow('revoked')})
it('rolls canary and prior targets back when a later health gate fails',async()=>{const target=fixture(),window=target.store.createWindow({projectId:target.project.id,name:'now',schedule:new Date(Date.now()-60_000).toISOString(),timezone:'UTC',durationMinutes:30,allowedOperations:['platform.upgrade'],requireApproval:true}),campaign=target.store.createCampaign({projectId:target.project.id,manifestId:target.manifest.id,windowId:window.id,fromVersion:'1.0.0',strategy:'canary',batchSize:1,healthGate:{path:'/health'},backupId:'verified-backup',targets:[{target:'canary',previousVersion:'1.0.0'},{target:'node-2',previousVersion:'1.0.0'}]}),rolledBack:string[]=[],driver:PlatformMaintenanceDriver={download:async()=>({path:'/verified/update',sha256:'a'.repeat(64)}),install:async()=>{},health:async({target})=>({healthy:target.target==='canary',evidence:{target:target.target}}),rollback:async({target})=>{rolledBack.push(target.target)}};expect(()=>target.service.enqueueCampaign(campaign.id)).toThrow('approval');target.service.enqueueCampaign(campaign.id,{approvedBy:target.actor.id});expect(await new DurableQueueWorker(target.service.queue,createMaintenanceQueueHandlers({store:target.store,platform:driver})).drain()).toMatchObject([{terminalState:'failed'}]);expect(rolledBack).toEqual(['node-2','canary']);expect(target.store.campaign(campaign.id)?.status).toBe('rolled_back');expect(target.store.targets(campaign.id).map(item=>item.status)).toEqual(['rolled_back','rolled_back'])})})
describe('cleanup and disaster recovery safety',()=>{it('requires a fresh immutable cleanup preview and exact confirmation',async()=>{const target=fixture(),removed:string[]=[],driver:CleanupDriver={kind:'artifacts',discover:async()=>[{id:'old-a',kind:'artifact',label:'Old A',bytes:10},{id:'old-b',kind:'artifact',label:'Old B',bytes:20}],remove:async candidate=>{removed.push(candidate.id)}},plan=await target.service.previewCleanup({projectId:target.project.id,kind:'artifacts',criteria:{olderThanDays:30}},[driver]);expect(plan).toMatchObject({status:'preview',estimatedBytes:30});expect(()=>target.service.enqueueCleanup(plan.id,'yes')).toThrow('Exact confirmation');target.service.enqueueCleanup(plan.id,'DELETE 2 artifacts');expect(await new DurableQueueWorker(target.service.queue,createMaintenanceQueueHandlers({store:target.store,cleanup:[driver]})).drain()).toMatchObject([{terminalState:'succeeded'}]);expect(removed).toEqual(['old-a','old-b']);expect(target.store.cleanup(plan.id)).toMatchObject({status:'succeeded',result:{reclaimedBytes:30}})})
it('restores only into isolation, measures objectives, and always verifies cleanup',async()=>{const target=fixture(),value=target.store.createDrill({projectId:target.project.id,scenario:'database',isolatedTarget:'isolated://drills/database',expectedRpoMinutes:60,expectedRtoMinutes:10}),events:string[]=[],driver:DisasterRecoveryDriver={scenario:'database',restore:async()=>{events.push('restore');return{target:'isolated://drills/restored',recoveryPointAt:new Date(Date.now()-5*60_000).toISOString(),evidence:{rows:100}}},verify:async()=>{events.push('verify');return{healthy:true,evidence:{check:'ok'}}},cleanup:async()=>{events.push('cleanup')}};target.service.enqueueDrill(value.id);expect(await new DurableQueueWorker(target.service.queue,createMaintenanceQueueHandlers({store:target.store,recovery:[driver]})).drain()).toMatchObject([{terminalState:'succeeded'}]);expect(events).toEqual(['restore','verify','cleanup']);expect(target.store.drill(value.id)).toMatchObject({status:'passed',cleanupVerified:true})})})
