# Bake a ts-cloud golden image as a Hetzner snapshot.
#
#   bun run scripts/build-image.ts        # generates ../recipe.sh
#   packer build images/packer/hetzner.pkr.hcl
#
# Then reference the snapshot id in cloud.config.ts:
#   compute: { image: '<snapshot-id>', bakedImage: true }

packer {
  required_plugins {
    hcloud = {
      source  = "github.com/hetznercloud/hcloud"
      version = ">= 1.5.0"
    }
  }
}

variable "hcloud_token" {
  type      = string
  default   = env("HCLOUD_TOKEN")
  sensitive = true
}

source "hcloud" "ubuntu" {
  token         = var.hcloud_token
  image         = "ubuntu-24.04"
  location      = "fsn1"
  server_type   = "cx22"
  ssh_username  = "root"
  snapshot_name = "ts-cloud-php-{{timestamp}}"
  snapshot_labels = {
    "ts-cloud/golden" = "php"
  }
}

build {
  sources = ["source.hcloud.ubuntu"]

  # The recipe installs the full ts-cloud stack (nginx, php-fpm, Composer,
  # services, hardening) — generated by `bun run scripts/build-image.ts`.
  provisioner "shell" {
    script = "../recipe.sh"
  }
}
