export const API_VERSION = '1.1.0'

export function openApiDocument(): Record<string, unknown> {
  const error = {
    type: 'object',
    required: ['error'],
    properties: { error: { type: 'object', required: ['code', 'message', 'requestId'], properties: { code: { type: 'string' }, message: { type: 'string' }, requestId: { type: 'string', format: 'uuid' }, details: {} } } },
  }
  const page = (schema: Record<string, unknown>) => ({
    type: 'object', required: ['data', 'page', 'requestId'], properties: { data: { type: 'array', items: schema }, page: { type: 'object', required: ['hasMore'], properties: { nextCursor: { type: 'string' }, hasMore: { type: 'boolean' } } }, requestId: { type: 'string', format: 'uuid' } },
  })
  const listResponses = (schema: Record<string, unknown>) => ({ '200': { description: 'A stable cursor page.', content: { 'application/json': { schema: page(schema) } } }, default: { $ref: '#/components/responses/Error' } })
  return {
    openapi: '3.1.0',
    info: { title: 'ts-cloud API', version: API_VERSION, description: 'Additive changes are released within v1. Breaking request or response changes require a new URL version.' },
    servers: [{ url: '/' }],
    security: [{ bearerAuth: [] }],
    paths: {
      '/api/v1/projects': { get: { operationId: 'listProjects', summary: 'List accessible projects', parameters: [{ $ref: '#/components/parameters/Limit' }, { $ref: '#/components/parameters/Cursor' }], responses: listResponses({ $ref: '#/components/schemas/Project' }) } },
      '/api/v1/projects/{projectId}/environments': { get: { operationId: 'listEnvironments', summary: 'List accessible project environments', parameters: [{ $ref: '#/components/parameters/ProjectId' }, { $ref: '#/components/parameters/Limit' }, { $ref: '#/components/parameters/Cursor' }], responses: listResponses({ $ref: '#/components/schemas/Environment' }) } },
      '/api/v1/services': { get: { operationId: 'listServices', summary: 'List accessible services', parameters: [{ name: 'projectId', in: 'query', required: true, schema: { type: 'string' } }, { name: 'environmentId', in: 'query', schema: { type: 'string' } }, { $ref: '#/components/parameters/Limit' }, { $ref: '#/components/parameters/Cursor' }], responses: listResponses({ $ref: '#/components/schemas/Service' }) } },
      '/api/v1/source/connections': {
        get: { operationId: 'listSourceConnections', summary: 'List safe Git connection metadata', parameters: [{ $ref: '#/components/parameters/Limit' }, { $ref: '#/components/parameters/Cursor' }], responses: listResponses({ $ref: '#/components/schemas/SourceConnection' }) },
        post: { operationId: 'createSourceConnection', summary: 'Create an encrypted Git connection', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['provider', 'name', 'host'], properties: { provider: { type: 'string', enum: ['github', 'gitlab', 'bitbucket', 'gitea', 'generic_https', 'generic_ssh'] }, name: { type: 'string' }, host: { type: 'string', format: 'uri' }, token: { type: 'string', writeOnly: true }, repositoryFullName: { type: 'string' }, repositoryUrl: { type: 'string' } } } } } }, responses: { '201': { description: 'Encrypted connection created.' }, default: { $ref: '#/components/responses/Error' } } },
        delete: { operationId: 'disconnectSourceConnection', summary: 'Preview or safely disconnect a Git connection', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['id'], properties: { id: { type: 'string' }, preview: { type: 'boolean' } } } } } }, responses: { '200': { description: 'Impact preview or disconnected connection.' }, default: { $ref: '#/components/responses/Error' } } },
      },
      '/api/v1/source/repositories': { get: { operationId: 'listSourceRepositories', summary: 'List or synchronize granted repositories', parameters: [{ name: 'connectionId', in: 'query', required: true, schema: { type: 'string' } }, { name: 'sync', in: 'query', schema: { type: 'boolean' } }, { name: 'search', in: 'query', schema: { type: 'string' } }, { $ref: '#/components/parameters/Limit' }, { $ref: '#/components/parameters/Cursor' }], responses: listResponses({ $ref: '#/components/schemas/SourceRepository' }) } },
      '/api/v1/source/refs': { get: { operationId: 'listSourceRefs', summary: 'List repository branches or tags', parameters: [{ name: 'connectionId', in: 'query', required: true, schema: { type: 'string' } }, { name: 'repository', in: 'query', required: true, schema: { type: 'string' } }, { name: 'repositoryId', in: 'query', schema: { type: 'string' } }, { name: 'type', in: 'query', schema: { type: 'string', enum: ['branches', 'tags'] } }], responses: { '200': { description: 'Provider reference page.' }, default: { $ref: '#/components/responses/Error' } } } },
      '/api/v1/source/bindings': { post: { operationId: 'createSourceBinding', summary: 'Bind a repository to an application', requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/SourceBindingRequest' } } } }, responses: { '201': { description: 'Source binding created.' }, default: { $ref: '#/components/responses/Error' } } } },
      '/api/v1/source/webhooks': { post: { operationId: 'createSourceWebhook', summary: 'Create and optionally reconcile a signed webhook', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['connectionId', 'repositoryFullName', 'baseUrl'], properties: { connectionId: { type: 'string' }, repositoryId: { type: 'string' }, repositoryFullName: { type: 'string' }, baseUrl: { type: 'string', format: 'uri' }, events: { type: 'array', items: { type: 'string', enum: ['push', 'pull_request'] } }, reconcile: { type: 'boolean' } } } } } }, responses: { '201': { description: 'Webhook endpoint created; endpoint is revealed once.' }, default: { $ref: '#/components/responses/Error' } } } },
      '/api/v1/deployments': { post: { operationId: 'createDeployment', summary: 'Queue a deployment', parameters: [{ name: 'Idempotency-Key', in: 'header', required: true, schema: { type: 'string', minLength: 8, maxLength: 128 } }], requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/DeploymentRequest' } } } }, responses: { '202': { description: 'Queued operation.', content: { 'application/json': { schema: { $ref: '#/components/schemas/OperationResponse' } } } }, default: { $ref: '#/components/responses/Error' } } } },
      '/api/v1/operations': { get: { operationId: 'listOperations', summary: 'List scoped operations', parameters: [{ name: 'projectId', in: 'query', schema: { type: 'string' } }, { $ref: '#/components/parameters/Limit' }, { $ref: '#/components/parameters/Cursor' }], responses: listResponses({ $ref: '#/components/schemas/Operation' }) } },
      '/api/v1/events': { get: { operationId: 'listEvents', summary: 'List scoped audit events', parameters: [{ name: 'projectId', in: 'query', schema: { type: 'string' } }, { name: 'after', in: 'query', schema: { type: 'integer', minimum: 0 } }, { $ref: '#/components/parameters/Limit' }], responses: listResponses({ $ref: '#/components/schemas/Event' }) } },
      '/api/v1/events/stream': { get: { operationId: 'streamEvents', summary: 'Stream scoped audit events', responses: { '200': { description: 'Authenticated server-sent event stream.', content: { 'text/event-stream': { schema: { type: 'string' } } } }, default: { $ref: '#/components/responses/Error' } } } },
      '/api/v1/openapi.json': { get: { operationId: 'getOpenApi', summary: 'Get the OpenAPI contract', security: [], responses: { '200': { description: 'OpenAPI 3.1 contract.' } } } },
    },
    components: {
      securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'tsc_v1' } },
      parameters: {
        Limit: { name: 'limit', in: 'query', schema: { type: 'integer', minimum: 1, maximum: 100, default: 50 } },
        Cursor: { name: 'cursor', in: 'query', schema: { type: 'string' } },
        ProjectId: { name: 'projectId', in: 'path', required: true, schema: { type: 'string' } },
      },
      responses: { Error: { description: 'Stable error envelope.', content: { 'application/json': { schema: error } } } },
      schemas: {
        Project: { type: 'object', required: ['id', 'slug', 'name'], properties: { id: { type: 'string' }, slug: { type: 'string' }, name: { type: 'string' }, description: { type: 'string' } } },
        Environment: { type: 'object', required: ['id', 'projectId', 'slug', 'name', 'kind'], properties: { id: { type: 'string' }, projectId: { type: 'string' }, slug: { type: 'string' }, name: { type: 'string' }, kind: { type: 'string' }, region: { type: 'string' } } },
        Service: { type: 'object', required: ['id', 'projectId', 'kind', 'slug', 'name'], properties: { id: { type: 'string' }, projectId: { type: 'string' }, environmentId: { type: 'string' }, kind: { type: 'string' }, slug: { type: 'string' }, name: { type: 'string' }, metadata: { type: 'object', additionalProperties: true } } },
        SourceConnection: { type: 'object', required: ['id', 'provider', 'name', 'host', 'status', 'credentialConfigured'], properties: { id: { type: 'string' }, provider: { type: 'string' }, name: { type: 'string' }, host: { type: 'string' }, status: { type: 'string' }, credentialConfigured: { type: 'boolean' }, credentialFingerprint: { type: 'string' }, grantedScopes: { type: 'array', items: { type: 'string' } } } },
        SourceRepository: { type: 'object', required: ['id', 'connectionId', 'fullName', 'cloneUrl', 'defaultBranch'], properties: { id: { type: 'string' }, connectionId: { type: 'string' }, fullName: { type: 'string' }, cloneUrl: { type: 'string' }, defaultBranch: { type: 'string' }, visibility: { type: 'string' }, archived: { type: 'boolean' } } },
        SourceBindingRequest: { type: 'object', additionalProperties: false, required: ['projectId', 'connectionId', 'repositoryFullName'], properties: { projectId: { type: 'string' }, environmentId: { type: 'string' }, resourceId: { type: 'string' }, connectionId: { type: 'string' }, repositoryId: { type: 'string' }, repositoryFullName: { type: 'string' }, defaultBranch: { type: 'string' }, branchRule: { type: 'string' }, tagRule: { type: 'string' }, monorepoRoot: { type: 'string' }, includePaths: { type: 'array', items: { type: 'string' } }, excludePaths: { type: 'array', items: { type: 'string' } }, submodules: { type: 'boolean' }, cloneDepth: { type: 'integer', minimum: 1 }, deployKeyId: { type: 'string' }, autoDeploy: { type: 'boolean' }, pullRequestPreviews: { type: 'boolean' } } },
        DeploymentRequest: { type: 'object', additionalProperties: false, required: ['projectId', 'environmentId'], properties: { projectId: { type: 'string' }, environmentId: { type: 'string' }, serviceId: { type: 'string' }, action: { type: 'string', enum: ['deploy', 'rollback'], default: 'deploy' }, revision: { type: 'string' } } },
        Operation: { type: 'object', required: ['id', 'state', 'kind', 'correlationId', 'createdAt'], properties: { id: { type: 'string' }, state: { type: 'string' }, kind: { type: 'string' }, correlationId: { type: 'string' }, createdAt: { type: 'string', format: 'date-time' } } },
        OperationResponse: { type: 'object', required: ['operation', 'idempotentReplay', 'requestId'], properties: { operation: { $ref: '#/components/schemas/Operation' }, idempotentReplay: { type: 'boolean' }, requestId: { type: 'string', format: 'uuid' } } },
        Event: { type: 'object', required: ['id', 'sequence', 'type', 'level', 'correlationId', 'createdAt'], properties: { id: { type: 'string' }, sequence: { type: 'integer' }, type: { type: 'string' }, level: { type: 'string' }, correlationId: { type: 'string' }, payload: {}, createdAt: { type: 'string', format: 'date-time' } } },
      },
    },
  }
}
