/**
 * Mail server provisioning — `mail`, the Zig SMTP/IMAP server, installed from
 * pantry and run as a systemd unit, with its own webmail UI.
 *
 * ## One binary, two jobs
 *
 * Development mail traps and production mail servers are conventionally two
 * different programs, and that difference is where mail breaks: a message that
 * renders in mailpit has been through a parser nothing in production will ever
 * run, and a `From` that mailpit accepts is one no MTA would. The bugs that
 * costs are the ones nobody can reproduce locally.
 *
 * So a `'catcher'` here is not a different program. It is the same binary with
 * delivery switched off, authentication switched off, bound to loopback, on
 * mailpit's ports — one parser, one Maildir, one UI, all the way from a
 * developer's laptop to production. See {@link ResolvedMailService}.
 *
 * ## What is deliberately not automated
 *
 * **DNS.** The MX, SPF and DMARC records, and the DKIM record for the key
 * generated below, are printed rather than published. They belong to a zone
 * this provisioner may not own, and a wrong MX does not fail — it silently
 * routes somebody's mail somewhere else, which is discovered days later by the
 * person who did not get it. {@link mailDnsRecords} returns them so the CLI
 * and the dashboard can show the same set.
 *
 * **The DKIM private key is generated once and never rewritten.** Regenerating
 * it on every provision would invalidate every signature already in flight,
 * so the key is created only when the file is absent.
 */

import type { ResolvedMailService } from '@ts-cloud/core'
import { PANTRY_PROJECT_DIR, buildPantryInstallScript, PANTRY_PACKAGES } from './package-manager'

/** Where the generated config, environment file and DKIM keys live. */
export const MAIL_CONFIG_DIR = '/etc/mail'

/** The unprivileged account the mail server runs as. */
export const MAIL_USER = 'mail-server'

/** systemd unit name, so callers can restart it without re-deriving the string. */
export const MAIL_UNIT = 'mail'

/** Where pantry exposes the installed `mail` binary. */
const PANTRY_BIN = `${PANTRY_PROJECT_DIR}/pantry/.bin`

/** Single-quote a value for safe embedding in generated shell. */
function sh(value: string | number): string {
  return `'${String(value).split("'").join("'\\''")}'`
}

/** Quote a value for a TOML string, which only needs `\` and `"` escaped. */
function toml(value: string): string {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
}

/** The package spec to install, honouring a pinned version. */
export function mailPackages(mail: ResolvedMailService): string[] {
  return [mail.version ? `${PANTRY_PACKAGES.mail}@${mail.version}` : PANTRY_PACKAGES.mail]
}

/** Absolute path of a domain's DKIM private key. */
export function dkimKeyPath(mail: ResolvedMailService, domain: string): string {
  return `${MAIL_CONFIG_DIR}/dkim/${domain}.${mail.dkim.selector}.pem`
}

/**
 * The mail server's `config.toml`.
 *
 * Only the keys the server actually reads (`packages/zig/src/core/config.zig`)
 * are written. Everything the TOML has no section for — webmail, IMAP, DKIM
 * keys, delivery method — goes in the environment file instead; see
 * {@link buildMailEnvFile}. Splitting them is not a choice, it is where the
 * server looks.
 */
export function buildMailConfigToml(mail: ResolvedMailService): string {
  const lines: string[] = [
    '# Generated by ts-cloud. Edits are overwritten on the next deploy —',
    '# change `services.mail` in the cloud config instead.',
    '',
    '[server]',
    `host = ${toml(mail.bindAddress)}`,
    `port = ${mail.ports.smtp}`,
    `hostname = ${toml(mail.hostname)}`,
  ]

  // `hostname` and its parent are local to the server already; only the extra
  // domains have to be listed, and listing the others too is harmless noise
  // that makes a support conversation shorter.
  if (mail.domains.length > 0)
    lines.push(`local_domains = ${toml(mail.domains.join(', '))}`)

  lines.push(
    `max_message_size = ${mail.maxMessageSize}`,
    '',
    '[tls]',
    `enabled = ${mail.tls.enabled}`,
  )

  if (mail.tls.certPath) lines.push(`cert_path = ${toml(mail.tls.certPath)}`)
  if (mail.tls.keyPath) lines.push(`key_path = ${toml(mail.tls.keyPath)}`)

  lines.push(
    '',
    '[auth]',
    // A catcher has no accounts. With auth on it would advertise AUTH and then
    // refuse every login, which reads to a mail client as a broken server
    // rather than as a trap that does not need one.
    `enabled = ${mail.mode === 'server'}`,
    '',
    '[antispam]',
    `dnsbl = ${mail.spam.dnsbl}`,
    `greylist = ${mail.spam.greylist}`,
    `spam_filter = ${mail.spam.enabled}`,
    `junk_score = ${mail.spam.junkScore}`,
    `reject_score = ${mail.spam.rejectScore}`,
    '',
    '[dkim]',
    `rotation_enabled = ${mail.dkim.enabled && mail.dkim.rotate}`,
    `rotation_interval_days = ${mail.dkim.rotateIntervalDays}`,
    '',
    '[acme]',
    `enabled = ${mail.tls.acme}`,
  )

  if (mail.tls.acmeEmail) lines.push(`email = ${toml(mail.tls.acmeEmail)}`)

  lines.push(
    '',
    '[webhook]',
    `enabled = ${!!mail.webhookUrl}`,
  )
  if (mail.webhookUrl) lines.push(`url = ${toml(mail.webhookUrl)}`)

  lines.push('')
  return lines.join('\n')
}

/**
 * The systemd `EnvironmentFile`.
 *
 * Everything the server configures through the environment rather than the
 * TOML: the webmail listener, IMAP and submission ports, DKIM keys, the
 * delivery method, and the database path.
 */
export function buildMailEnvFile(mail: ResolvedMailService): string {
  const lines: string[] = [
    '# Generated by ts-cloud. See /etc/mail/config.toml for the rest.',
    `SMTP_DB_PATH=${mail.storagePath}/mail.db`,
    `SMTP_DELIVERY_METHOD=${mail.delivery === 'ses' ? 'ses' : 'direct'}`,
  ]

  if (mail.delivery === 'ses') lines.push(`SMTP_SES_REGION=${mail.sesRegion}`)

  if (mail.ports.submission) lines.push(`SUBMISSION_PORT=${mail.ports.submission}`)
  if (mail.ports.submissions) lines.push(`SMTPS_PORT=${mail.ports.submissions}`)

  if (mail.ports.imap) {
    lines.push('IMAP_ENABLED=1', `IMAP_PORT=${mail.ports.imap}`)
  }

  if (mail.webmail.enabled) {
    lines.push(
      'SMTP_ENABLE_WEBMAIL=true',
      `SMTP_WEBMAIL_PORT=${mail.webmail.port}`,
      // A catcher is reached over plain HTTP on loopback. A Secure cookie is
      // dropped by the browser on such a connection, so the UI would take a
      // login and then behave as though nobody had logged in.
      `SMTP_WEBMAIL_SECURE_COOKIES=${mail.tls.enabled}`,
    )
  }

  if (mail.tls.requireForAuth) lines.push('SMTP_REQUIRE_TLS_FOR_AUTH=true')

  if (mail.dkim.enabled && mail.domains.length > 0) {
    const [primary, ...rest] = mail.domains
    lines.push(
      `DKIM_DOMAIN=${primary}`,
      `DKIM_SELECTOR=${mail.dkim.selector}`,
      `DKIM_PRIVATE_KEY_PATH=${dkimKeyPath(mail, primary)}`,
    )
    // Each additional domain signs with its own `d=`, which is what DMARC
    // alignment needs — one shared key would align for one domain and fail for
    // the others.
    if (rest.length > 0) {
      const extra = rest.map(domain => `${domain}:${mail.dkim.selector}:${dkimKeyPath(mail, domain)}`)
      lines.push(`DKIM_EXTRA_KEYS=${extra.join(',')}`)
    }
  }

  lines.push('')
  return lines.join('\n')
}

/** The systemd unit that runs the server. */
export function buildMailUnit(mail: ResolvedMailService): string {
  // Ports below 1024 need the capability; a catcher on 1025/8025 does not, and
  // is not given it. Granting it unconditionally would hand a process that
  // accepts anonymous mail the right to bind anything.
  const privileged = [mail.ports.smtp, mail.ports.submission, mail.ports.submissions, mail.ports.imap, mail.ports.imaps]
    .some(port => typeof port === 'number' && port < 1024)

  return [
    '[Unit]',
    'Description=Mail server (SMTP/IMAP + webmail)',
    'After=network-online.target',
    'Wants=network-online.target',
    '',
    '[Service]',
    'Type=simple',
    `User=${MAIL_USER}`,
    `Group=${MAIL_USER}`,
    `WorkingDirectory=${mail.storagePath}`,
    `EnvironmentFile=${MAIL_CONFIG_DIR}/mail.env`,
    `Environment="PATH=${PANTRY_BIN}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"`,
    `ExecStart=${PANTRY_BIN}/mail serve --config ${MAIL_CONFIG_DIR}/config.toml`,
    'Restart=always',
    'RestartSec=5',
    // A busy server holds a socket per connection plus its Maildir handles;
    // the default 1024 is reached by a modest delivery burst.
    'LimitNOFILE=65536',
    ...(privileged ? ['AmbientCapabilities=CAP_NET_BIND_SERVICE', 'CapabilityBoundingSet=CAP_NET_BIND_SERVICE'] : []),
    'NoNewPrivileges=true',
    'PrivateTmp=true',
    'ProtectSystem=strict',
    'ProtectHome=true',
    'ProtectKernelTunables=true',
    'ProtectKernelModules=true',
    'ProtectControlGroups=true',
    // Under ProtectSystem=strict the whole filesystem is read-only, so the two
    // directories the server writes have to be named or it cannot store a
    // single message.
    `ReadWritePaths=${mail.storagePath} ${MAIL_CONFIG_DIR}`,
    '',
    '[Install]',
    'WantedBy=multi-user.target',
    '',
  ].join('\n')
}

/** A DNS record an operator has to publish for mail to work. */
export interface MailDnsRecord {
  type: 'MX' | 'TXT' | 'CNAME'
  /** Record name, e.g. `example.com` or `default._domainkey.example.com`. */
  name: string
  /**
   * Record value. For DKIM this is a placeholder — the real one is derived
   * from the public key on the box, which does not exist until provisioning
   * has run. The shell prints the actual value; see {@link buildDkimScript}.
   */
  value: string
  /** MX preference, when the type is MX. */
  priority?: number
  /** Why this record exists, shown beside it wherever it is presented. */
  note: string
}

/**
 * The records an operator has to publish. Returned rather than created: see
 * the module comment for why DNS is not automated here.
 */
export function mailDnsRecords(mail: ResolvedMailService): MailDnsRecord[] {
  // A catcher receives nothing from the internet and sends nothing to it.
  if (!mail.enabled || mail.mode !== 'server') return []

  const records: MailDnsRecord[] = []

  for (const domain of mail.domains) {
    // `hostname` is the server itself; an MX pointing a host at itself is
    // correct but redundant beside the parent domain's, and publishing it is
    // how a `mail.example.com` mailbox ends up unreachable when only the
    // parent's MX was updated. Both are listed so neither is forgotten.
    records.push({
      type: 'MX',
      name: domain,
      value: mail.hostname,
      priority: 10,
      note: 'Where mail for this domain is delivered. Must resolve to this box.',
    })
    records.push({
      type: 'TXT',
      name: domain,
      value: `v=spf1 mx -all`,
      note: 'SPF: only this domain\'s MX may send for it. Widen before adding another sender.',
    })
    records.push({
      type: 'TXT',
      name: `_dmarc.${domain}`,
      // `p=none` deliberately: a policy that quarantines starts discarding
      // mail the moment SPF or DKIM is misconfigured, and the first week of a
      // new mail server is exactly when they are.
      value: `v=DMARC1; p=none; rua=mailto:postmaster@${domain}`,
      note: 'DMARC in report-only mode. Tighten to p=quarantine once reports are clean.',
    })

    if (mail.dkim.enabled) {
      records.push({
        type: 'TXT',
        name: `${mail.dkim.selector}._domainkey.${domain}`,
        value: 'v=DKIM1; k=rsa; p=<public key printed during provisioning>',
        note: `DKIM. The value is printed by the provision step and read from ${dkimKeyPath(mail, domain)}.`,
      })
    }
  }

  return records
}

/**
 * Generate a DKIM key per domain, once, and print the record to publish.
 *
 * Guarded on the file's absence rather than on a flag: a re-provision that
 * regenerated the key would invalidate every signature already in flight, and
 * the mail affected is mail that was already accepted by somebody's server and
 * is now failing verification at their end.
 */
export function buildDkimScript(mail: ResolvedMailService): string[] {
  if (!mail.dkim.enabled || mail.domains.length === 0) return []

  const lines = [`mkdir -p ${MAIL_CONFIG_DIR}/dkim`]

  for (const domain of mail.domains) {
    const key = dkimKeyPath(mail, domain)
    lines.push(
      `if [ ! -f ${sh(key)} ]; then openssl genrsa -out ${sh(key)} 2048; fi`,
      `chmod 0600 ${sh(key)}`,
      // The record's value is the public key with the PEM envelope and every
      // newline removed — printed here because the operator has to copy it into
      // a zone, and reconstructing it by hand from the PEM is where people
      // paste a truncated key.
      `echo "DKIM ${mail.dkim.selector}._domainkey.${domain} IN TXT v=DKIM1; k=rsa; p=$(openssl rsa -in ${sh(key)} -pubout -outform PEM 2>/dev/null | grep -v '^-----' | tr -d '\\n')"`,
    )
  }

  lines.push(`chown -R ${MAIL_USER}:${MAIL_USER} ${MAIL_CONFIG_DIR}/dkim`)
  return lines
}

/**
 * Create the declared mailboxes.
 *
 * Both `create` and `change-password` run, unconditionally, and that is not
 * belt-and-braces. `mail user:local create` on an existing account prints
 * "already exists" and **exits 0**, so a `create || change-password` chain
 * would never reach the second command — an operator who rotated a password in
 * the config and redeployed would get a box that kept the old one and reported
 * success. Running both means the declaration is the truth on every deploy.
 *
 * Each is tolerated failing so one bad account cannot abort a provision that
 * has already installed and started the server, and each runs as the service
 * account with the server's own `SMTP_DB_PATH` — as root it would create a
 * second database beside the one the server reads, and the accounts would
 * exist in a file nothing opens.
 */
export function buildMailAccountScript(mail: ResolvedMailService): string[] {
  if (mail.accounts.length === 0) return []

  const cli = (args: string) =>
    `runuser -u ${MAIL_USER} -- env SMTP_DB_PATH=${sh(`${mail.storagePath}/mail.db`)} ${PANTRY_BIN}/mail user:local ${args} || true`

  return mail.accounts.flatMap(account => [
    cli(`create ${sh(account.address)} ${sh(account.password)} ${sh(account.address)}`),
    cli(`change-password ${sh(account.address)} ${sh(account.password)}`),
  ])
}

/**
 * The whole provisioning sequence for the mail service.
 *
 * Idempotent throughout: every step is guarded, so this runs on a cold boot,
 * on a golden-image bake, and on every redeploy with the same result. Returns
 * `[]` when mail is not declared.
 */
export function buildMailProvisionScript(mail: ResolvedMailService): string[] {
  if (!mail.enabled) return []

  return [
    ...buildPantryInstallScript(mailPackages(mail) as any),
    // A system account with no login shell and no home of its own. The server
    // refuses nothing if run as root, which is exactly why it must not be: it
    // parses attacker-supplied bytes on an open port.
    `id -u ${MAIL_USER} >/dev/null 2>&1 || useradd --system --no-create-home --shell /usr/sbin/nologin ${MAIL_USER}`,
    `mkdir -p ${mail.storagePath} ${MAIL_CONFIG_DIR}`,
    `chown -R ${MAIL_USER}:${MAIL_USER} ${mail.storagePath}`,
    `cat > ${MAIL_CONFIG_DIR}/config.toml <<'TS_CLOUD_MAIL_CONF_EOF'`,
    buildMailConfigToml(mail),
    'TS_CLOUD_MAIL_CONF_EOF',
    `cat > ${MAIL_CONFIG_DIR}/mail.env <<'TS_CLOUD_MAIL_ENV_EOF'`,
    buildMailEnvFile(mail),
    'TS_CLOUD_MAIL_ENV_EOF',
    // The env file holds account and DKIM paths, and on a server the ACME
    // contact. Readable by the service, by nobody else.
    `chmod 0640 ${MAIL_CONFIG_DIR}/mail.env`,
    `chown root:${MAIL_USER} ${MAIL_CONFIG_DIR}/mail.env`,
    ...buildDkimScript(mail),
    `cat > /etc/systemd/system/${MAIL_UNIT}.service <<'TS_CLOUD_MAIL_UNIT_EOF'`,
    buildMailUnit(mail),
    'TS_CLOUD_MAIL_UNIT_EOF',
    'systemctl daemon-reload',
    `systemctl enable ${MAIL_UNIT}`,
    `systemctl restart ${MAIL_UNIT}`,
    // Accounts are created against the database the server just initialised,
    // so they come after the start rather than before it.
    ...buildMailAccountScript(mail),
  ]
}
