import type { ControlPlaneOperation, ControlPlaneStore, JsonValue } from '../control-plane'
import type { ReleaseRecord } from './types'
import { DurableOperationQueue } from '../queue'
import { ReleaseStore } from './store'

export class ReleaseService { readonly releases: ReleaseStore; readonly queue: DurableOperationQueue; constructor(readonly controlPlane: ControlPlaneStore) { this.releases = new ReleaseStore(controlPlane); this.queue = new DurableOperationQueue(controlPlane) }
  enqueueActivation(release: ReleaseRecord, input: { actorId?: string, action?: 'activate' | 'rollback', targetReleaseId?: string } = {}): ControlPlaneOperation { if (!['built', 'failed', 'rolled_back', 'superseded'].includes(release.status)) throw new Error(`Release ${release.status} cannot be activated`); const action = input.action ?? 'activate'; const operation = this.queue.enqueue({ projectId: release.projectId, environmentId: release.environmentId, resourceId: release.resourceId, actorId: input.actorId, kind: `release.${action}`, idempotencyKey: `release:${release.id}:${action}:${release.rollbackAttempts}`, correlationId: `release:${release.id}`, input: { releaseId: release.id, targetReleaseId: input.targetReleaseId ?? null }, lockKey: `resource:${release.resourceId}`, providerKey: this.controlPlane.getResource(release.resourceId)?.provider ?? 'default', maxAttempts: release.automaticRollback ? 2 : 1, retryClasses: ['network', 'provider_throttled', 'provider_unavailable'], resumePolicy: 'fail', cancellationMode: 'provider_non_cancellable', retentionDays: 365 }).operation; this.releases.transition(release.id, 'activating', { message: `${action} queued.`, operationId: operation.id, trafficPercent: 0 }); return operation }
  completeHealthGate(releaseId: string, input: { healthy: boolean, operationId?: string, health?: JsonValue, message?: string }): { release: ReleaseRecord, rollbackOperation?: ControlPlaneOperation } { const release = this.releases.get(releaseId); if (!release || release.status !== 'activating') throw new Error('Release is not activating'); if (input.healthy) return { release: this.releases.transition(release.id, 'active', { message: input.message ?? 'Health gate passed; activation completed.', operationId: input.operationId, trafficPercent: 100, health: input.health }) }; const failed = this.releases.transition(release.id, 'failed', { message: input.message ?? 'Health gate failed.', operationId: input.operationId, trafficPercent: 0, health: input.health }); const previous = release.previousReleaseId ? this.releases.get(release.previousReleaseId) : undefined; if (!release.automaticRollback || release.rollbackAttempts >= 1 || !previous) return { release: failed }; const rollbackOperation = this.queue.enqueue({ projectId: release.projectId, environmentId: release.environmentId, resourceId: release.resourceId, kind: 'release.rollback', idempotencyKey: `release:${release.id}:automatic-rollback`, correlationId: `release:${release.id}`, input: { releaseId: release.id, targetReleaseId: previous.id, automatic: true }, lockKey: `resource:${release.resourceId}`, providerKey: this.controlPlane.getResource(release.resourceId)?.provider ?? 'default', maxAttempts: 1, retryClasses: [], resumePolicy: 'fail', cancellationMode: 'provider_non_cancellable', retentionDays: 365 }).operation; return { release: failed, rollbackOperation } }
}
